server:
  port: 8080   # Gateway runs on 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: asset-service
          uri: http://localhost:8083
          predicates:
            - Path=/asset-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8085
          predicates:
              - Path=/order-service/**
          filters:
            - StripPrefix=1
        - id: trade-service
          uri: http://localhost:8086
          predicates:
            - Path=/trade-service/**
          filters:
            - StripPrefix=1
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: asset-service
#        url: /asset-service/api/v3/api-docs
        url: /asset-service/v3/api-docs
      - name: pricing-service
        url: /pricing-service/v3/api-docs