server:
  port: 8087
spring:
  application:
    name: report-service
  logging:
    file:
      name: logs/report-service.log
    level:
      root: INFO
  kafka:
    bootstrap-servers: 172.18.92.130:9092
    consumer:
      group-id: report-service-v3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    report-command: "report-command"
    report-events: "report-events"
  partitions: 3
  replication-factor: 1