server.port=8083
spring.application.name=pricing-service
logging.file.name=logs/pricing-service.log
logging.level.root=INFO
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.jpa.hibernate.ddl-auto=validate