server:
  port: 8084
spring:
  application:
    name: pricing-service
  logging:
    file:
      name: logs/pricing-service.log
    level:
      root: INFO
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    jpa:
      hibernate:
        ddl-auto: validate
pricing:
  assets:
    - repo
    - tba
  thresholds:
    repo: 1000.0
    tba: 500.0
  scheduler:
    rate: 60000   # run every 1 mins(milliseconds)