server:
  port: 8085
spring:
  main:
    web-application-type: servlet
  logging:
    file:
      name: logs/order-service.log
    level:
      root: INFO
  datasource:
    url: jdbc:postgresql://localhost:5432/asset-management
    username: postgres
    password: shipra123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: asset_mgmt
  kafka:
    bootstrap-servers: 172.18.92.130:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #properties:
        #spring.json.add.type.headers: false
    consumer:
      group-id: order-service-v3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.selflearning.messaging.events"
        spring.json.use.type.headers: true
kafka:
  topics:
    order-created: "order-created"
    trade-execution: "trade-execution"
    report-command: "report-command"
    report-events: "report-events"
  partitions: 3
  replication-factor: 1